# Evaluation metrics configuration for the ACM system.
#
# Defines:
# 1. Metrics thresholds for consciousness evaluation
# 2. Progress tracking parameters
# 3. Development stage transitions
# 4. Integration test configurations
#
# Dependencies:
# - models/evaluation/consciousness_monitor.py
# - models/core/consciousness_metrics.py
# - tests/test_consciousness_metrics.py

# Consciousness Metrics Configuration
metrics:
  consciousness:
    min_score: 0.0
    max_score: 1.0
    emergence_threshold: 0.7

  emotional:
    coherence_threshold: 0.65
    stability_threshold: 0.60
    adaptation_rate: 0.15

  attention:
    base_threshold: 0.5
    stress_multiplier: 1.5
    decay_rate: 0.05
