# Evaluation metrics configuration for the ACM system.
# Defines:
# 1. Metrics thresholds for consciousness evaluation
# 2. Progress tracking parameters
# 3. Development stage transitions
# 4. Integration test configurations

# Consciousness Metrics Configuration
metrics:
  consciousness:
    min_score: 0.0
    max_score: 1.0
    emergence_threshold: 0.7

  emotional:
    coherence_threshold: 0.65
    stability_threshold: 0.60
    adaptation_rate: 0.15

  attention:
    base_threshold: 0.5
    stress_multiplier: 1.5
    decay_rate: 0.05

memory_metrics:
  meta_memory:
    stability_threshold: 0.75
    novelty_threshold: 0.25
    min_weight: 0.1
    max_weight: 0.95

  pattern_recognition:
    min_confidence: 0.7
    temporal_coherence: 0.8
    emotional_alignment: 0.6

emotional_metrics:
  processing:
    base_stability: 0.5
    coherence_threshold: 0.7
    adaptation_rate: 0.01

  integration:
    narrative_alignment: 0.8
    emotional_resonance: 0.7
    memory_coherence: 0.75

narrative_metrics:
  llama:
    min_confidence: 0.8
    coherence_threshold: 0.7
    adaptation_rate: 0.01
    max_context_length: 4096

  # LoRA adjustment unified with main config (rank=16 there).
  lora:
    alpha: 32
    update_threshold: 0.1
    min_update_interval: 100

consciousness_metrics:
  system:
    attention_threshold: 0.6
    stability_threshold: 0.8
    coherence_minimum: 0.7

  development:
    learning_rate: 0.001
    meta_learning_rate: 0.0001
    emotional_growth: 0.5
    narrative_stability: 0.7

imagination_metrics:
  constraints:
    reality_alignment: 0.8
    emotional_bounds: 0.7
    memory_influence: 0.6

  creative:
    novelty_threshold: 0.3
    coherence_minimum: 0.6
    stability_required: 0.7

# Foundation Model Metrics
foundation_model:
  narrator:
    coherence_threshold: 0.75
    adaptation_rate: 0.01
    context_length: 4096
    stability_check_interval: 100

  integration:
    emotional_alignment: 0.7
    memory_coherence: 0.75
    imagination_bounds: 0.8

meta_memory:
  novel_experiences:
    min_weight: 0.1
    max_weight: 0.95
    reinforcement_rate: 0.2

  pattern_stability:
    min_confidence: 0.7
    temporal_coherence: 0.8
    emotional_resonance: 0.6

emotional_processing:
  baseline:
    stability_threshold: 0.75
    coherence_threshold: 0.7
    adaptation_rate: 0.01

  fusion:
    modality_alignment: 0.8
    narrative_resonance: 0.7
    memory_influence: 0.6

development_tracking:
  consciousness:
    attention_threshold: 0.6
    stability_threshold: 0.8
    coherence_minimum: 0.7

  adaptation:
    learning_rate: 0.001
    meta_learning_rate: 0.0001
    emotional_growth: 0.5
