# configs/reinforcement.yaml

reinforcement:
  emotional_scale: 2.0 # Weight for emotional rewards
  dreamer_config:
    hidden_size: 256
    learning_rate: 0.0001
    gamma: 0.99
    lambda_gae: 0.95

  memory_config:
    capacity: 100000
    batch_size: 64

  narrative_config:
    model: "llama-3.3"
    max_length: 128
